Modify bundling to create universal dev_bundle
	Builder for an universal dev_bundle to run meteor also on different architectures like ARM.
	This universal bundle is able to use pre-installed platform binaries for node and mongo.
	Run meteor inofficially on ARMv6l and ARMv7l architecture like RaPi and UDOO and others.

diff --git a/meteor b/meteor
--- a/meteor
+++ b/meteor
@@ -10,6 +10,8 @@ if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
     exit 1
 fi
 
+UNIVERSAL_ARCH=
+
 if [ "$UNAME" = "Darwin" ] ; then
     if [ "i386" != "$(uname -p)" -o "1" != "$(sysctl -n hw.cpu64bit_capable 2>/dev/null || echo 0)" ] ; then
 
@@ -22,9 +24,21 @@ if [ "$UNAME" = "Darwin" ] ; then
 elif [ "$UNAME" = "Linux" ] ; then
     ARCH="$(uname -m)"
     if [ "$ARCH" != "i686" -a "$ARCH" != "x86_64" ] ; then
-        echo "Unsupported architecture: $ARCH"
-        echo "Meteor only supports i686 and x86_64 for now."
-        exit 1
+        # test for platform installed binaries
+        if [ "$(which node)" != "" -a "$(which npm)" != "" -a "$(which mongo)" != "" -a "$(which mongod)" != "" ] ; then
+            # we are using installation for platform installed binaries
+            ARCH="${ARCH}_universal"
+            UNIVERSAL_ARCH=$(uname -a)
+        else
+            echo "Unsupported architecture: $ARCH"
+            echo "Meteor only supports i686 and x86_64 or universal for now."
+            echo "To use universal architecture make sure that the necessary binaries are pre-installed."
+            # get status of installed binaries
+            for TEST_PACKAGE in node npm mongo mongod ; do
+                echo -e "\tcheck $TEST_PACKAGE: \c"; [[ "$(which $TEST_PACKAGE)" != "" ]] && echo "ok" || echo "fail"
+            done
+            exit 1
+        fi
     fi
 fi
 PLATFORM="${UNAME}_${ARCH}"
